<?php
$helper         = $this->helper('Magepow\DisplayUpsell\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
if( !$isEnabled ) return;
$objectManager      = \Magento\Framework\App\ObjectManager::getInstance();
$limit       = $helper->getConfigModule('general/limit');
$title       = $helper->getConfigModule('general/title');
$productName = $helper->getConfigModule('general/show_name');
$price       = $helper->getConfigModule('general/show_price');
$addtocart   = $helper->getConfigModule('general/addtocart');
$addtowishlist   = $helper->getConfigModule('general/addtowishlist');
$addtocompare    = $helper->getConfigModule('general/addtocompare');
$sku        = $helper->getConfigModule('general/sku');
$productSku = $objectManager->create('\Magento\Catalog\Model\ProductRepository')->get($sku);
$skuId      = $productSku ->getId();
$upsellProductItem  = $this->getUpsellProducts();
$upsellProductItems = array_unique($upsellProductItem);
$upSellProducts     = array_slice($upsellProductItems,0,$limit);
array_unshift($upSellProducts,$skuId);
$image              = 'new_products_content_widget_grid';
 
?>
<?php if ($upSellProducts && count($upSellProducts) > 0): ?>
<div id="cms-static-upsell-products" class="cms-static-upsell-products upsell-products">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">   
               <div class="upsell-content">
                    <div class="block-title title">
                        <strong id="block-upsell-heading" class="block-upsell" role="heading" aria-level="2"><?php echo $title; ?></strong>
                    </div>
                    <div class="productUpsell products wrapper grid products-grid" data-infinite="true" data-autoplay="true" data-autoplay-speed="2000" data-dots="true" data-speed="300" data-slides-To-Show="4",data-slides-To-Scroll="1",data-space="15" data-responsive= '[{"breakpoint": "1024", "settings": {"slidesToShow": "4"}}, {"breakpoint": "800", "settings": {"slidesToShow": "3"}}, {"breakpoint": "600", "settings": {"slidesToShow": "2"}}, {"breakpoint": "460", "settings": {"slidesToShow": "1"}}]'>
                        <?php foreach ($upSellProducts as $upSellProduct) : ?>
                            <?php $product = $objectManager->create('Magento\Catalog\Model\Product')->load($upSellProduct); ?>
                            <ol class="item product product-item" >
                                <div class="product-item-info ">
                                    <div class="images-container">
                                        <div class="product name product-item-link" href="<?php echo $product->getProductUrl();?>">   <?php if ($productName): ?>
                                                <h2 class="product-name">
                                                    <a class="product-item-link" title="<?php echo $product->getName();?>" href="<?php echo $product->getProductUrl();?>"><?php echo $product->getName();?></a>
                                                </h2>
                                            <?php endif ?>
                                        </div>
                                        <div class="product-hover">
                                            <a href="<?php echo $product->getProductUrl();?>" class="product photo product-item-photo">
                                                
                                                <span class="product-image-container">
                                                    <span class="product-image-wrapper">
                                                        <?= $block->getImage($product,$image)->toHtml() ?>
                                                    </span>
                                            </a>
                                        </div>
                                        <div class="hover-box">
                                            <div class="product actions">
                                            <div class="price-box price-final_price">
                                                <span class="price-container price-final_price" >
                                                    <span class="price-wrapper ">
                                                        <?php if ($price): ?>
                                                            <span class="price">
                                                                <?= $block->getProductPrice($product) ?>
                                                            </span>    
                                                        <?php endif ?>
                                                    </span>
                                                </span>
                                            </div>
                                            <div class="actions-primary">
                                                <?php if ($addtocart): ?>
                                                    <?php if ($product->isSaleable()): ?>
                                                        <?php if ($product->getTypeInstance()->hasRequiredOptions($product)): ?>
                                                            <?php echo $block->getBlockHtml('formkey')?>
                                                            <button class="action tocart primary button btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php  echo $block->getAddToCartUrl($product) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
                                                                    <i class="icon icon-add-to-cart"></i>
                                                                    <span><?php echo __('Add to Cart') ?>
                                                                    </span>
                                                            </button>
                                                        <?php else: ?>
                                                            <form data-role="tocart-form" action="<?php echo $objectManager->get('\Magento\Catalog\Block\Product\ListProduct')->getAddToCartUrl($product);; ?>" method="post"> 
                                                                <div class="btn">
                                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                                    <button type="submit" title="Add to Cart" class="action tocart primary button btn-cart" type="submit" title="<?php echo __('Add to Cart') ?>">
                                                                        <i class="icon icon-add-to-cart"></i>
                                                                        <span>Add to Cart</span>
                                                                    </button>
                                                                </div>   
                                                            </form>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                <?php endif ?>
                                                    <div class="add-to-links actions-secondary" data-role="add-to-links">
                                                            <?php if ($addtocompare): ?>
                                                                <a href="#" class="action tocompare"
                                                                   data-post='<?php echo $this->helper('Magento\Catalog\Helper\Product\Compare')->getPostDataParams($product);?>'
                                                                   data-role="add-to-links"
                                                                   title="<?php echo __('Add to Compare'); ?>">
                                                                    <i class="icon icon-compare"></i><?php echo __('Compare') ?>
                                                                </a>
                                                            <?php endif ?>
                                                            <?php if ($addtowishlist): ?>
                                                                <a href="#" data-post='<?php echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wishlist') ?>">
                                                                    <i class="icon icon-favorites"></i><?php echo __('Wishlist') ?>
                                                                </a>
                                                            <?php endif ?>
                                            
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </ol>
                        <?php endforeach; ?>
                    </div> 
                </div> 
            </div>
        </div>
    </div>   
</div> 
<?php endif ?>  
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Magento_Ui/js/core/app": {
                        "components": {
                            "wishlist": {
                                "component": "Magento_Wishlist/js/view/wishlist"
                            }
                        }
                    }
                }
            }
        </script>
        <script type="text/javascript">
             require([ 'jquery', 'magiccart/slick', 'alothemes', ], function($, slick, alothemes){ 
                var productUpsell = $('.upsell-content .productUpsell');
                 if(productUpsell.length) $('head').append(magicproduct(productUpsell, '.item')); });
        </script>
    